// src/components/DetailView.vue
<template>
  <div class="detailview">
    <div v-for="field in fields" class="detailview__item">
      <div class="detailview__label">{{field.label}}</div>
      <DetailValue class="detailview__value" :value="field.value" @change="updateValue(field.label, $event)"></DetailValue>
    </div>
  </div>
</template>

<script>
import DetailValue from './DetailValue'

export default {
  components: { DetailValue },
  props: {
    inspector: Object
  },
  computed: {
    fields () {
      const fields = []

      // Object.keys(this.selected).forEach(property => {
      //   if (property[0] === '_' || ['children', 'parent', 'worldTransform'].indexOf(property) !== -1) {
      //     return
      //   }
      //   var value = this.selected[property]
      //   var type = typeof value
      //   if (type === 'string' || type === 'number') {
      //     fields.push({ label: property, value: value })
      //   } else if (type === 'boolean') {
      //     fields.push({ label: property, value: value ? 'true' : 'false' })
      //   } else if (value === null) {
      //     fields.push({ label: property, value: 'null' })
      //   } else if (type === 'object') {
      //     Object.keys(value).forEach(_property => {
      //       var _value = value[_property]
      //       var _type = typeof _value
      //       if (_type === 'string' || _type === 'number') {
      //         fields.push({ property: property + '.' + _property, value: _value })
      //       } else if (_type === 'boolean') {
      //         fields.push({ property: property + '.' + _property, value: _value ? 'true' : 'false' })
      //       } else {
      //         fields.push({ property: property + '.' + _property, value: '...' + _type })
      //       }
      //     })
      //   } else {
      //     fields.push({ property: property, value: '...' + type })
      //   }
      // })
      return fields
    }
  },
  methods: {
    updateValue (property, value) {
      this.proxy.eval('$pixi.' + property + ' = ' + value)
    }
  }
}
</script>

<style lang="scss">
.detailview {
  // white-space: nowrap;
  padding: 4px;
}

.detailview__item {
  display: flex;
  margin-bottom: 2px;
}

.detailview__label {
  display: inline-block;
  color: #c00;
  padding-right: 5px;
  &:after {
    content: ':';
    color: #000;
  }
}

.detailview__value {
  color: #333;
}
</style>

// src/components/DetailView.jsx
import {Component} from "react";
import DetailValue from './DetailValue';
import proxy from '../services/proxy';
import refresh from '../services/refresh';

require("./DetailView.scss");

export default class DetailView extends Component {
	render() {
		var data = this.props.data;
		var formatted = {};
		Object.keys(data).forEach( property => {
			if (property[0] === '_' || ['children', 'parent', 'worldTransform'].indexOf(property) !== -1) {
				return;
			}
			var value = data[property];
			var type = typeof value;
			if (type === 'string' || type === 'number') {
				formatted[property] = value
			} else if (type === 'boolean') {
				formatted[property] = value ? 'true' : 'false'
			} else if (value === null) {
				formatted[property] = 'null';
			} else if (type === 'object') {
				Object.keys(value).forEach( _property => {
					var _value = value[_property];
					var _type = typeof _value;
					if (_type === 'string' || _type === 'number') {
						formatted[property + '.' + _property] = _value
					} else if (_type === 'boolean') {
						formatted[property + '.' + _property] = _value ? 'true' : 'false'
					} else {
						formatted[property + '.' + _property] = '...' + _type
					}
				})
			} else {
				formatted[property] = '...' + type
			}
		});
		var fields = [];
		for (var label in formatted) {
			var value = formatted[label]; 
			fields.push(<div key={label}>
				<span className="detailview__label">{label}</span>
				<DetailValue className="detailview__value" onChange={this.updateValue.bind(this, label)} value={value}/>
			</div>);
		}
		return <div className="detailview">{fields}</div> 
	}
	updateValue(property, value) {
        proxy.eval("$pixi." + property + " = " + value);
	}
};
