// src/components/PixiPanel.jsx
require("./PixiPanel.scss");
var {Component} = require("react");
var {Observable} = require("rx");
var PixiTree = require("./PixiTree");
var DetailView = require("./DetailView");
var SplitView = require("./SplitView");
var Toggle = require("./Toggle");
var Toolbar = require("./Toolbar");
var scene = require("../services/scene");
var refresh = require("../services/refresh");
var detectPixi = require("../services/detectPixi");
var proxy = require("../services/proxy");
var inspectorProxy = require("../services/inspectorProxy");

// require('../pixi.inspector'); // Enable for live reload
var DEBUG = false;

class PixiPanel extends Component {
	constructor(props) {
		super(props)
		this.state = {
			tree: false,
			mode: 'NORMAL',
			selected: false,
			pixiDetected: false
		};
	}
	render() {
		var tree = this.state.tree;
		var reboot = DEBUG ? <span onClick={this.reboot}>[ reboot {this.state.error} ]</span> : <span>{this.state.error}</span>;
		if (!tree) {
			return <div className="pixi-panel__message">{reboot} {this.state.pixiDetected ? 'Connecting to Pixi...' : 'Looking for Pixi...'}</div>
		}
		var selected = this.state.selected;
		var selectedId = selected ? selected._inspector.id : false;
		var hoverId = this.state.hover;
		var context = this.state.context || {};
		return <span className="pixi-panel">{reboot}
			<Toolbar><Toggle icon="node-search" value={this.state.selectMode} onChange={this.toggleSelectMode.bind(this)} title="Select a node in the scene to inspect it"/></Toolbar>
			<SplitView>
				<PixiTree tree={tree} selectedId={selectedId} hoverId={hoverId} context={context} />
				{selected ? <DetailView data={selected} />: ''}
			</SplitView>
		</span>
	}
	componentDidMount() {
		this.subscriptions = [
			scene.subscribe( (scene) => {
				this.setState(scene);
			}, error => {
				proxy.eval('typeof window.__PIXI_INSPECTOR_GLOBAL_HOOK__').then(function (type) {
					if (type === 'object') {
						console.error(error);
				 	} else { // page refresh?
					 	location.reload();
					}
				})
				
			}),
			detectPixi.subscribe( (path) => {
				this.setState({pixiDetected: path });
			}),
			Observable.interval(500).subscribe(refresh)
		];
	}
	componentWillUnmount() {
		this.subscriptions.forEach( (subscription) => {
			subscription.dispose();
		});
	}
	toggleSelectMode(value) {
		inspectorProxy.selectMode(value);
	}
	reboot() {
		location.reload();
	}
};
module.exports = PixiPanel;

// src/components/PixiPanel.vue
<template>
  <div class="pixi-panel">
    <Toolbar>
      <Toggle icon="node-search"
              :value="selectMode"
              @change="toggleSelectMode"
              title="Select a node in the scene to inspect it"></Toggle>
      <a @click="reboot">reconnect</a>
    </Toolbar>
    <div class="pixi-panel__message"
         v-if="!isDetected">
      Looking for PixiJS ...
    </div>
    <div class="pixi-panel__message"
         v-if="isDetected && !isConnected">
      Connecting to PixiJS ...
    </div>
    <SplitView class="pixi-panel__body">
      <TreeView :scene="scene"
                :inspector="inspector"
                v-if="scene"></TreeView>
      <DetailView :selected="selected"
                  :proxy="inspector.proxy"
                  v-if="selected"></DetailView>
    </SplitView>
  </div>
</template>

<script>
import { Observable } from 'rxjs/Observable'
import Toolbar from './Toolbar'
import Toggle from './Toggle'
import SplitView from './SplitView'
import TreeView from './TreeView'
import DetailView from './DetailView'
import reboot$ from '../services/reboot$'
import detectPixi$ from '../services/detectPixi$'
import injectInspector from '../services/injectInspector'

export default {
  components: { Toolbar, Toggle, SplitView, TreeView, DetailView },
  data: () => ({
    isDetected: false,
    isConnected: false,
    selectMode: false,
    scene: null,
    selected: null,
    inspector: null
  }),
  mounted () {
    this.inspector$ = reboot$.startWith('initial').switchMap(() => {
      this.isDetected = false
      this.isConnected = false
      this.scene = null
      this.selected = null
      return detectPixi$.switchMap(config => {
        this.isDetected = true
        return injectInspector(config)
      }).do(() => {
        this.isConnected = true
      })
    }).do(inspector => {
      this.inspector = inspector
    }).catch(error => {
      console.error(error)
      reboot$.next('error')
      return Observable.empty()
    }).publishReplay(1).refCount()

    this.$subscribeTo(this.inspector$.switchMap(inspector => {
      // return Observable.empty()
      return Observable.interval(500).map(() => inspector.refresh$)
    }), refresh$ => {
      refresh$.next('interval')
    })
    const scene$ = this.inspector$.switchMap(inspector => inspector.scene$)
    this.$subscribeTo(scene$, scene => {
      // console.log(scene)
      this.selectMode = scene.selectMode
      this.selected = scene.selected
      this.scene = scene
    })
  },
  methods: {
    toggleSelectMode (value) {
      this.selectModeSubscription = this.inspector$.first().subscribe(inspector => {
        inspector.selectMode(value)
      })
    },
    reboot () {
      window.location.reload()
    }
  }

  // },
  // componentDidMount() {
  // this.subscriptions = [
  //   scene.subscribe((_scene) => {
  //   this.setState(_scene)
  //   }, error => {
  //   proxy.eval('typeof window.__PIXI_INSPECTOR_GLOBAL_HOOK__').then(function (type) {
  //     if (type === 'object') {
  //     console.error(error)
  //     } else { // page refresh?
  //     location.reload()
  //     }
  //   })
}
</script>

<style lang="scss">
.pixi-panel {
  cursor: default;
  font-size: 11px !important;
  font-family: Menlo, monospace;
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100vh;
}

.pixi-panel__message {
  height: 100%;
  font-size: 24px;
  color: rgb(75%, 75%, 75%);
  font-weight: bold;
  padding: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.pixi-panel__body {
  flex-grow: 1;
}
</style>
